{
	"version": 1733067737,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/nessupermariobrosworld3-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tilemap.png",
		"images/daun-sheet0.png",
		"images/daun-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/platformstage2.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/bgstage22.png",
		"images/detail.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite18-sheet1.png",
		"images/sprite19-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/spritefont.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/sprite30-sheet1.png",
		"images/charaspawn-sheet0.png",
		"images/tilemap2.png",
		"images/tilemap4.png",
		"images/sprite32-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite35-sheet1.png",
		"images/sprite35-sheet2.png",
		"images/sprite36-sheet0.png",
		"images/sprite37-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite40-sheet1.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/sprite42-sheet1.png",
		"images/sprite43-sheet0.png",
		"images/sprite43-sheet1.png",
		"images/sprite44-sheet0.png",
		"images/sprite44-sheet1.png",
		"images/sprite45-sheet0.png",
		"images/sprite46-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/sprite48-sheet0.png",
		"images/sprite49-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite51-sheet0.png",
		"images/sprite52-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/sprite55-sheet0.png",
		"images/sprite56-sheet0.png",
		"images/sprite57-sheet0.png",
		"images/sprite60-sheet0.png",
		"images/sprite61-sheet0.png",
		"images/sprite62-sheet0.png",
		"images/sprite63-sheet0.png",
		"images/sprite64-sheet0.png",
		"images/sprite65-sheet0.png",
		"images/sprite66-sheet0.png",
		"images/sprite68-sheet0.png",
		"images/sprite69-sheet0.png",
		"images/sprite70-sheet0.png",
		"images/sprite71-sheet0.png",
		"images/sprite72-sheet0.png",
		"images/sprite73-sheet0.png",
		"images/chatbar-sheet0.png",
		"images/sprite75-sheet0.png",
		"images/sprite67-sheet0.png",
		"images/start-sheet0.png",
		"images/sprite76-sheet0.png",
		"images/sprite76-sheet1.png",
		"images/nyxara-sheet0.png",
		"images/nyxara-sheet1.png",
		"images/nyxara-sheet2.png",
		"images/sprite77-sheet0.png",
		"images/sprite77-sheet1.png",
		"images/cavebg1-sheet0.png",
		"images/sprite79-sheet0.png",
		"images/sprite80-sheet0.png",
		"images/sprite81-sheet0.png",
		"images/sprite84-sheet0.png",
		"images/sprite85-sheet0.png",
		"images/sprite86-sheet0.png",
		"images/sprite87-sheet0.png",
		"images/sprite88-sheet0.png",
		"images/sprite89-sheet0.png",
		"images/sprite90-sheet0.png",
		"images/20240713dragonhelpbuttonsheet-sheet0.png",
		"images/sprite83-sheet0.png",
		"images/nextframe-sheet0.png",
		"images/alenframe-sheet0.png",
		"images/alenportrait-sheet0.png",
		"images/sprite94-sheet0.png",
		"images/sprite95-sheet0.png",
		"images/20240707dragontabasheet2-sheet0.png",
		"images/buku-sheet0.png",
		"images/sprite91-sheet0.png",
		"images/backframe-sheet0.png",
		"images/sprite96-sheet0.png",
		"images/caveplat.png",
		"images/room1-sheet0.png",
		"images/pmbuka1-sheet0.png",
		"images/sprite97-sheet0.png",
		"images/sprite98-sheet0.png",
		"images/sprite99-sheet0.png",
		"images/imageremovebgpreview-sheet0.png",
		"images/gandalfhardcoreplatformerassets-sheet0.png",
		"images/sprite100-sheet0.png",
		"images/sprite102-sheet0.png",
		"images/sprite102-sheet1.png",
		"images/sprite102-sheet2.png",
		"images/sprite92-sheet0.png",
		"images/sprite101-sheet0.png",
		"images/lapis-sheet0.png",
		"images/mousecursor-sheet0.png",
		"images/sprite104-sheet0.png",
		"images/sprite104-sheet1.png",
		"images/tilemap6.png",
		"images/sprite53-sheet0.png",
		"images/sprite105-sheet0.png",
		"images/sprite108-sheet0.png",
		"images/sprite109-sheet0.png",
		"images/sihir-sheet0.png",
		"images/sihir-sheet1.png",
		"images/portalstage2-sheet0.png",
		"images/lapis2-sheet0.png",
		"images/lapis3-sheet0.png",
		"images/lapis4-sheet0.png",
		"images/sprite114-sheet0.png",
		"images/sprite115-sheet0.png",
		"images/sprite116-sheet0.png",
		"images/portalstage3-sheet0.png",
		"images/lava1-sheet0.png",
		"images/sprite111-sheet0.png",
		"images/sprite119-sheet0.png",
		"media/yt1s.com - undertale ost 014  heartache.m4a",
		"media/yt1s.com - undertale ost 014  heartache.ogg",
		"media/yt1scom-sword-slash-sound-effects-mani-creation_jeajxhvk.m4a",
		"media/yt1scom-sword-slash-sound-effects-mani-creation_jeajxhvk.ogg",
		"media/yt1s.com - 全ての人の魂の戦い ush ver.m4a",
		"media/yt1s.com - 全ての人の魂の戦い ush ver.ogg",
		"media/pedang kena.m4a",
		"media/pedang kena.ogg",
		"media/yt1s (mp3cut.net).m4a",
		"media/yt1s (mp3cut.net).ogg",
		"media/ffiostlich&krakenbossthemes(bossbattlea).m4a",
		"media/ffiostlich&krakenbossthemes(bossbattlea).ogg",
		"media/serang.m4a",
		"media/serang.ogg",
		"media/kena hit.m4a",
		"media/kena hit.ogg",
		"media/hehh.m4a",
		"media/hehh.ogg",
		"media/mati.m4a",
		"media/mati.ogg",
		"media/yt1s (mp3cut.net)_2.m4a",
		"media/yt1s (mp3cut.net)_2.ogg",
		"media/yt1s start.m4a",
		"media/yt1s start.ogg",
		"media/final fantasy iv ds ost  - land of dwarves_2.m4a",
		"media/final fantasy iv ds ost  - land of dwarves_2.ogg",
		"media/pause.m4a",
		"media/pause.ogg",
		"media/yt1s save.m4a",
		"media/yt1s save.ogg",
		"media/load2.m4a",
		"media/load2.ogg",
		"media/void.m4a",
		"media/void.ogg",
		"media/paper-2.m4a",
		"media/paper-2.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/buku open.m4a",
		"media/buku open.ogg",
		"media/quest notiv.m4a",
		"media/quest notiv.ogg",
		"media/voice test (enhanced) (mp3cut.net).m4a",
		"media/voice test (enhanced) (mp3cut.net).ogg",
		"media/alen 1 (enhanced).m4a",
		"media/alen 1 (enhanced).ogg",
		"media/alen 2 (enhanced).m4a",
		"media/alen 2 (enhanced).ogg",
		"media/alen 3 (enhanced).m4a",
		"media/alen 3 (enhanced).ogg",
		"media/alen 4 (enhanced).m4a",
		"media/alen 4 (enhanced).ogg",
		"media/alen 5 (enhanced).m4a",
		"media/alen 5 (enhanced).ogg",
		"media/undertale ost - good night.m4a",
		"media/undertale ost - good night.ogg",
		"media/nyx 1 (enhanced).m4a",
		"media/nyx 1 (enhanced).ogg",
		"media/nyx 2 (enhanced).m4a",
		"media/nyx 2 (enhanced).ogg",
		"media/nyx 3 (enhanced).m4a",
		"media/nyx 3 (enhanced).ogg",
		"media/nyx 4 (mp3cut.net) (enhanced).m4a",
		"media/nyx 4 (mp3cut.net) (enhanced).ogg",
		"media/nyx 5 (enhanced).m4a",
		"media/nyx 5 (enhanced).ogg",
		"media/collect.m4a",
		"media/collect.ogg",
		"media/tele.m4a",
		"media/tele.ogg",
		"media/persona 4 -reincarnation- i'll face myself -battle- (mp3cut.net).m4a",
		"media/persona 4 -reincarnation- i'll face myself -battle- (mp3cut.net).ogg",
		"media/nyx 6 (enhanced).m4a",
		"media/nyx 6 (enhanced).ogg",
		"media/nyx 7 (enhanced).m4a",
		"media/nyx 7 (enhanced).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}